FROM oven/bun AS base

FROM base AS prune
RUN bun add -g turbo
WORKDIR /app
COPY . .
RUN turbo prune @hc/bun-worker --docker

FROM base AS build
WORKDIR /app
COPY --from=prune /app/out/json/ .
COPY --from=prune /app/bun.lock ./bun.lock
RUN bun install
COPY --from=prune /app/out/full/ .
COPY tsconfig.base.json .

FROM oven/bun:slim AS runtime
WORKDIR /app
COPY --from=build /app .
CMD ["bun", "run", "apps/bun-worker/src/index.ts"]
