FROM oven/bun AS base

FROM base AS prune
RUN bun add -g turbo
WORKDIR /app
COPY . .
RUN turbo prune @hc/sv-web --docker

FROM base AS install
WORKDIR /app
COPY --from=prune /app/out/json/ .
RUN bun install

FROM base AS build
WORKDIR /app
COPY --from=install /app/node_modules ./node_modules
COPY --from=prune /app/out/full/ .
COPY tsconfig.base.json .
RUN bun run --filter @hc/sv-web build

FROM oven/bun:slim AS runtime
WORKDIR /app
COPY --from=build /app/apps/sv-web/build ./build
COPY --from=build /app/node_modules ./node_modules
EXPOSE 8080
ENV PORT=8080
CMD ["bun", "run", "build/index.js"]